CMAKE_MINIMUM_REQUIRED(VERSION 3.11)

if (NOT SDL2_TTF_FOUND)
  INCLUDE(FetchContent)
  if (WIN32)
    FetchContent_Declare(SDL2_TTF URL https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.20.1/SDL2_ttf-2.20.1.tar.gz)
  else()
    FetchContent_Declare(SDL2_TTF URL https://github.com/BastienBoymond/SDL_ttf/archive/refs/tags/1.0.tar.gz)
  endif()
  FetchContent_GetProperties(SDL2_TTF)
  if (NOT SDL2_TTF_POPULATED)
    SET(FETCHCONTENT_QUIET NO)
    FetchContent_Populate(SDL2_TTF)
    SET(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
    ADD_SUBDIRECTORY(${sdl2_ttf_SOURCE_DIR} ${sdl2_ttf_BINARY_DIR})
    SET(SDL2_TTF_FOUND TRUE)
  endif()
endif()
